const bgPage = chrome.extension.getBackgroundPage(); // Get background page for extension
const searchUI = new SearchUI();
const bgSearchClass = bgPage.gSetSearchUI(searchUI);
const bgQueue = bgPage.gGetQueue();
const modal = new ModalClass(); // set up a modal class for a options, warnings or details
/**
 * Starts the search crazy UI and prepares all the search triggers.
 */
function startSearchCrazy() {
/** Detect when user closes page so background page can remove anything it doesn't need without the search UI. **/
window.addEventListener("beforeunload", (e) => { bgPage.gSetSearchUI(null); bgSearchClass.originRemove(); });
  searchUI.prepareSearch();
  bgSearchClass.addTrigger("rid", {"name":"Job Spotter", "rid":"ASOSP45W2WM03", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"C-SATS, Inc", "rid":"A15ZSKX8TUCGEU", "gid":"", "duration": 15000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Unanimous", "rid":"A1OVB3ATBAQ1KM", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Ipsoft", "rid":"A2NPHK2GTUF78O", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Picsfromabove", "rid":"ALZUWU3P4QQSG", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Alegion", "rid":"A8DQXJEVAM6JF", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Ipsoft2", "rid":"A1KHBXVBU8SRQ0", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Joe Lo", "rid":"A2CIK5WEHBJBNU", "gid":"", "duration": 10000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Vacation Rental API", "rid":"A2QKOWG2NKRJ2K", "gid":"", "duration": 20000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Geohive Admin", "rid":"A2RAGWQ0G2TWAT", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Ben Peterson", "rid":"AFEG4RKNBSL4T", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Remesh", "rid":"A32BFAN07OQKZN", "gid":"", "duration": 10000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"PickFu", "rid":"AI2HRFAYYSAW7", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Peter Burke", "rid":"A1UZ1H4REEV6MR", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Tim Kowalewski", "rid":"A3NVZ6RW9GT7CA", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"SocialCat", "rid":"A33KPKIGB3LRZD", "gid":"", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Endor", "rid":"ANER3VNU9AD0O", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Meghan Moore", "rid":"A1HLORNYQ43JYS", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"paul connor", "rid":"A3643USXULLFI2", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Emily Wilson", "rid":"A19Y8N1023GB2R", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Marketing Team", "rid":"A1X47GCK2IDEX3", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("rid", {"name":"Matthew Shardlow", "rid":"A3S0VV664CKQDA", "gid":"", "duration": 6000, "once":true, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Ibotta, Inc.", "rid":"", "gid":"30B721SJLR5BYYBNQJ0CVKKCWQZ0OI", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Javan Martin", "rid":"", "gid":"3BDJRSQX56L109G3MO1MNB1V5GL8S5", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Mturk Prod short video", "rid":"", "gid":"3HHMCOI47E84O2S8KPM5S1B08CHVSA", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Mturk Prod short video", "rid":"", "gid":"3YNFDCZ5R5PFFIJM3909SACR15RRNT", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Mturk Prod short video", "rid":"", "gid":"3S1POB7GVA8SY7OVNVNV1FUGCCLUQJ", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel compare", "rid":"", "gid":"3T6UNEUZ5USN3YJ7HC3S3YVC8S2911", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel (1-2 items)", "rid":"", "gid":"35DAEVU8JHJ10FFZ10EN4CRDQ8F870", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel (1-2 items)", "rid":"", "gid":"35DAEVU8JHJ10FFZ10EN4CRDQ8N878", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel (1-2 items)", "rid":"", "gid":"3T6HLR4BXW65EY3SGXC7I8IJLT5985", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel (1-2 items)", "rid":"", "gid":"3L8V324VIVRQCOOFCXM8V9CTK3H9FD", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Panel Classify Receipt", "rid":"", "gid":"37ZHE2JT1D250TKIB56TICN73UQ88W", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":true, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"Michael Thaler", "rid":"", "gid":"3T9YKFMCGXSGJFSWM9VI7I124UNC9X", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
  bgSearchClass.addTrigger("gid", {"name":"EMP Lab", "rid":"", "gid":"3D3X1L1OBIFIZZ22WGODAUDYQUR1VF", "duration": 6000, "once":false, "limitNumQueue":0, "limitTotalQueue":0, "limitFetches":0, "autoGoHam":false, goHamDuration:0, "tempGoHam":3000, "disabled":false, "from":"searchUI"});
}
/** ================ First lines executed when page is loaded. ============================ **/
allTabs('/searchCrazy.html', count => { // Count how many Search Crazy pages are opened.
  if (count<2) startSearchCrazy(); // If there are less than 2 pages opened then start loading data.
  else haltScript(null, 'You have SearchCrazy Max running in another tab or window. You can\'t have multiple instances running or it will cause database problems.', null, 'Error starting SearchCrazy Max', true);
});
